### PR TITLE
Improvements from professor

### PR DESCRIPTION
**Pull request by J0hanna01**
Improved until now 2/4:
*app/src/androidTest/java/se2/group3/gameoflife/frontend/MainActivityTest.java --> testname
*app/src/test/java/se2/group3/gameoflife/frontend/MainViewModelUnitTest.java --> testname

### CODE REVIEW

**Review by thomas-schleicher — COMMENTED** [review]
looks good

**Comment by J0hanna01** [comment]
@AyaSafan @Haxe33 @nzhurat 
💯 Friendly reminder 💯 
Please give me a short review if it is okay :)

**Review by nzhurat — APPROVED** [review]
great

**Review by Haxe33 — APPROVED** [review]
lgtm

**Pull request merged**
